services:
    app:
        volumes:
            - ${FILES_FOLDER_PATH}:/app/public/library/files:rw
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:
