services:
    app:
        build:
            target: dev
            args:
                UID: ${UID?}
                GID: ${GID?}
        environment:
            - CADDY_GLOBAL_OPTIONS=debug
        volumes:
            - ./:/app
    database:
        networks:
            - default
    mailer:
        image: axllent/mailpit
        ports:
        - "1025"
        - "8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
