
services:
  app:
      image: ${IMAGE_NAME}:${IMAGE_TAG}
      build:
          context: .
          target: prod
      depends_on:
          database:
              condition: service_healthy
      environment:
          - SERVER_NAME
          - MERCURE_PUBLISHER_JWT_KEY
          - MERCURE_SUBSCRIBER_JWT_KEY
      networks:
          - default
          - db-proxy
###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_PUBLISHER_JWT_KEY:-ChangeThisMercureHubJWTSecretKey}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_SUBSCRIBER_JWT_KEY:-ChangeThisMercureHubJWTSecretKey}'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:7000
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - default
      - db-proxy
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${DATABASE_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${DATABASE_NAME:-app}", "-U", "${DATABASE_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - db-proxy

volumes:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
    default: ~
    db-proxy:
        internal: true
